### ISSUE TITLE
Header Bar too big

### ISSUE THREAD

**Issue by H3rby7** [robotopia-x/robotopia#100]
I like the new Header bar, but it also takes a lot of space. I would suggest hiding it when being on a game page (thus map and editor being displayed.  

![image](https://cloud.githubusercontent.com/assets/5808849/23162224/6454368a-f82d-11e6-9875-03f6d074c828.png)

**Comment by paulsonnentag** [comment]
We could make it a little bit smaller but I think we can spare a few pixel to have a little bit more branding. I was also planning on using it as a menu bar to put general actions. I don't think we should get completely rid of it.

**Comment by timgrossmann** [comment]
I'd center the Text instead of having it at the lower border and probably caps it, like the logo...

**Comment by H3rby7** [comment]
Alright if we are actually using some of that space that's cool

**Comment by paulsonnentag** [comment]
I tried centering it but it looked weird because of the antenna of the robot.

**Comment by timgrossmann** [comment]
@paulsonnentag Ahh, ok 👍 I made it Caps and centered it, can be easily undone it's in my current branch

<img width="304" alt="screen shot 2017-02-22 at 19 39 30" src="https://cloud.githubusercontent.com/assets/16529337/23226665/a7a469be-f936-11e6-8c78-c690f57aae3a.png">
