### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by CristianRM7** [robotopia-x/robotopia#130]
Hi, first, great work, I've tried the web version and I love it. I tried installing it on an Ubuntu 16.04 (this also wanted to ask, any system preference to install this program?). And the installation is correct but when I run (npm start) I get "Error: Can not find module ./node_modules/action-overlay". Any idea how to fix it?

Thank you very much!

**Comment by paulsonnentag** [comment]
I looked into it and the dependencies were setup weirdly. I've fixed that. Can you checkout the current version on master and try again. If this doesn't fix your problem: What version of node and npm are you using?

**Comment by CristianRM7** [comment]
Perfect! Already the problems of the dependencies have been solved. I installed it well (only with 3 warnings) in ubuntu 16.04.2, npm version 3.5.2 and node version 4.2.6
Thanks for everything!
