### ISSUE TITLE
Installing Robotopia

### ISSUE THREAD

**Issue by amurciarenr** [robotopia-x/robotopia#131]
I've install Robotopia follwing this steps that I found in the web:

```
git clone https://github.com/robotopia-x/robotopia.git
cd robotopia
npm install
npm start
```

When I did 'npm start' this error appeared:

```
> robot-ide@0.1.0 start /Users/amurcia/robotopia
> budo index.js:bundle.js

sh: budo: command not found

npm ERR! Darwin 16.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! robot-ide@0.1.0 start: `budo index.js:bundle.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the robot-ide@0.1.0 start script 'budo index.js:bundle.js'.
npm ERR! This is most likely a problem with the robot-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     budo index.js:bundle.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls robot-ide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amurcia/robotopia/npm-debug.log

```

What's wrong?

**Comment by gmolledaj** [comment]
Eraro npm install: ├── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc
Kaj en npm start: > robot-ide@0.1.0 start /home/go/git/robotopia
> budo index.js:bundle.js

/usr/bin/env: «node»: No existe el archivo o el directorio

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! robot-ide@0.1.0 start: `budo index.js:bundle.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the robot-ide@0.1.0 start script 'budo index.js:bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robot-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     budo index.js:bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robot-ide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robot-ide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/go/git/robotopia/npm-debug.log

**Comment by gmolledaj** [comment]
npm-debug.log:
cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle robot-ide@0.1.0~prestart: robot-ide@0.1.0
6 silly lifecycle robot-ide@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle robot-ide@0.1.0~start: robot-ide@0.1.0
8 verbose lifecycle robot-ide@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle robot-ide@0.1.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/go/git/robotopia/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle robot-ide@0.1.0~start: CWD: /home/go/git/robotopia
11 silly lifecycle robot-ide@0.1.0~start: Args: [ '-c', 'budo index.js:bundle.js' ]
12 info lifecycle robot-ide@0.1.0~start: Failed to exec start script
13 verbose stack Error: robot-ide@0.1.0 start: `budo index.js:bundle.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid robot-ide@0.1.0
15 verbose cwd /home/go/git/robotopia
16 error Linux 4.4.0-72-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error robot-ide@0.1.0 start: `budo index.js:bundle.js`
24 error spawn ENOENT
25 error Failed at the robot-ide@0.1.0 start script 'budo index.js:bundle.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the robot-ide package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     budo index.js:bundle.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs robot-ide
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls robot-ide
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by paulsonnentag** [comment]
Normally [budo](https://github.com/mattdesl/budo) should be installed as a dev dependency when you run `npm install`. Can you try installing budo globally:

```
npm install -g budo
```

**Comment by stritti** [comment]
> Normally budo should be installed as a dev dependency when you run npm install. Can you try installing budo globally:
> 
> `npm install -g budo`

This is now also mentioned in Readme.md (PR https://github.com/robotopia-x/robotopia/pull/137)
