### ISSUE TITLE
Customize robot

### ISSUE THREAD

**Issue by CristianRM7** [robotopia-x/robotopia#133]
Hi! I seen in the first slide (http://slides.com/pguth/robotopia-x#/) that the robot is customized (it is not the standard robot, it's Rick!) How can this be done? 
Thanks!

**Comment by timgrossmann** [comment]
@CristianRM7 We're sorry, these were just development assets. We took them out of the project for copyright reasons

**Comment by CristianRM7** [comment]
I understand it is normal. I do not know if you will have left any trace of it, since it was doing tests with the competition mode. I create a scenario and when I enter (as a student) that scenario, it remains continuously loading and in the terminal I miss several errors that can not load some images (images that do not exist). Attached is a screenshot for you to see.

![images](https://cloud.githubusercontent.com/assets/27137764/25072767/e3abed68-22d7-11e7-89b9-6e972f70bd92.PNG)

**Comment by timgrossmann** [comment]
@CristianRM7 Ohh wow, thank you for that!
I think we'll have to look into that...

**Comment by CristianRM7** [comment]
You're welcome! It occurs when a student attempts to enter a group that the teacher has created.

**Comment by CristianRM7** [comment]
Hi. Is there an update planned? With the errors of the images the multiplayer challenge does not finish loading for example. Thank you very much

**Comment by paulsonnentag** [comment]
I'm sorry. I haven't worked on the project very actively. I promise I'll fix it this weekend. Cool to see that you still care about the project.

**Comment by CristianRM7** [comment]
Many thanks! I find it a very interesting project! Thank you!

**Comment by paulsonnentag** [comment]
I'm not quite sure why its not working. I fixed the missing images not loading, but that wasn't the cause of the problem. If I run it locally on my machine it works, but the online version at http://robotopia.co doesn't  connect to the client. Just wanted to give you an update, going to look into fixing the online version later.

**Comment by CristianRM7** [comment]
Ok Paul, thank you very much, to see if you give with it, it is a fantastic project!
