### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [robotopia-x/robotopia#140]
Hello, today while exploring GitHub looking for interesting projects found yours and I would love to contribute by designing a logo for it. I'm a designer in development and an open source enthusiast. We would be working together to create the design that fits best. Of course it's totally free and you can quit whenever you want. In case you agree, please let me know any preferences you may have about colors, shapes, etc you may have.  

Kind regards.

**Comment by timgrossmann** [comment]
@jorlogicus Hey 👋 
Thank you for your issue and the offer.

Unfortunately, we are currently not actively working on this project anymore.
Feel free to still work on a logo and do some design work if you're interested, we'd really appreciate it.

If you're also interested in a little bit less educational, **non-related project**, checkout out [InstaPy](https://github.com/timgrossmann/InstaPy).   
We are actively searching for designers that are eager to learn and want to contribute to Open-Source projects.
We are currently [searching for a new logo](https://github.com/timgrossmann/InstaPy/issues/3706) for a derivate of InstaPy. We'd love to have a designer who's interested in helping out, not only with a logo but maybe even UI designs for our new GUI etc.
The project has quite a wide reach (currently around 30k views/week).

Would love if you could [join our discord channel](
https://discord.gg/FDETsht) to have a chat if you're interested 😊
