### ISSUE TITLE
Add marker level

### ISSUE THREAD

**Issue by paulsonnentag** [robotopia-x/robotopia#68]
Estimate: `5 points`
- [x] Level 1: Robot places marker. Event Handling is already implemented
- [x] Level 2: Robot places marker at Resource. Event Handling is not implemented

**Comment by H3rby7** [comment]
Will be part of:  
https://github.com/robotopia-x/robotopia/tree/tutorialRedesign

I have some Ideas, so we don't need the user to place markers by clicking. I hope that way we can smoothly introduce this feature without breaking our own game principles.

**Comment by H3rby7** [comment]
implemented with: 30224463cb9d48af1b4731adc05f77dd0058ea5b
