### ISSUE TITLE
Disabled Blocks in Tutorials

### ISSUE THREAD

**Issue by H3rby7** [robotopia-x/robotopia#90]
In the Tutorial Levels we don't have the "on Start" block resulting in the behaviour shown in the screenshot.  
![image](https://cloud.githubusercontent.com/assets/5808849/23092944/f0268a8c-f5d5-11e6-9fdb-6310390f4bfe.png)

The first block gets disabled and does not get executed. the other blocks connected to it are not disabled and are executed.  

I would favor to be able to turn the functionality of blocks being disabled ON/OFF.  
This way we don't confuse the player at the start until we introduce the different events and routines.

**Comment by paulsonnentag** [comment]
Its a bug that only the first block is deactivated. They should be all deactivated. I would add the start block to all tutorials. That way we have a consistent semantic throughout the game. I don't really like the default behaviour of blockly that non connected blocks are combined from left to right, top to bottom.

**Comment by H3rby7** [comment]
I agree consistency is important, I just hope it doesn't get people confused.

**Comment by timgrossmann** [comment]
The start blocks are added in #87 😉

**Comment by H3rby7** [comment]
done by: 6a380df8aeb815f74e155ff96ea6d7d2c8de321f
